### ISSUE TITLE
Name 'self' not defined on fresh setup

### ISSUE THREAD

**Issue by hdslave** [osi1880vr/deforum-sd-ui#29]
I did a fresh git clone to catch up with the commits, & I get this error after setting up env & running. I was hoping to test the video functions with ffmpeg files in correct place after reading thru the last ,now closed, video issue
P.s really excited and enthusiastic about this this project!!

2022-09-26 11:30:22.786 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Ecco.Aqua\.conda\envs\ldm\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Ecco.Aqua\git\deforum-sd-ui\scripts\webui_streamlit.py", line 126, in <module>
    layout()
  File "C:\Users\Ecco.Aqua\git\deforum-sd-ui\scripts\webui_streamlit.py", line 99, in layout
    pluginModule = importlib.import_module(f"scripts.ui.{plugin[:-3]}")
  File "C:\Users\Ecco.Aqua\.conda\envs\ldm\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Ecco.Aqua\git\deforum-sd-ui\scripts\ui\noodletab.py", line 6, in <module>
    from scripts.tools.blocks import *
  File "C:\Users\Ecco.Aqua\git\deforum-sd-ui\scripts\tools\blocks.py", line 278, in <module>
    self.set_interface(name='2Image', value=output_images[0])
NameError: name 'self' is not defined

**Comment by saruzaru** [comment]
i have the same problem
