### ISSUE TITLE
'outputs/_node_drawers/' not found

### ISSUE THREAD

**Issue by MrPalais** [osi1880vr/deforum-sd-ui#39]
2022-09-29 08:47:20.904 Uncaught app exception
Traceback (most recent call last):
  File "V:\anaconda3\envs\deforum\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 562, in _run_script
    exec(code, module.__dict__)
  File "V:\_AI\_GENERATION\SD-DEFORUM\deforum-sd-ui-UP2DATE\scripts\webui_streamlit.py", line 219, in <module>
    layout()
  File "V:\_AI\_GENERATION\SD-DEFORUM\deforum-sd-ui-UP2DATE\scripts\webui_streamlit.py", line 162, in layout
    plugins[k][0].layoutFunc()
  File "V:\_AI\_GENERATION\SD-DEFORUM\deforum-sd-ui-UP2DATE\scripts\ui\noodletab.py", line 112, in layoutFunc
    drawerlist = listdirs(drawerPath)
  File "V:\_AI\_GENERATION\SD-DEFORUM\deforum-sd-ui-UP2DATE\scripts\ui\noodletab.py", line 74, in listdirs
    return [d for d in os.listdir(folder) if os.path.isdir(os.path.join(folder, d))]
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: 'outputs/_node_drawers/'

**Comment by osi1880vr** [comment]
Yeah we are still in the process to manage all the different folders in a way they are created if not present, please be patient and create them yourself if missing. Most the time the error comes from a missing folder not from missing code. as soon as the folder is present it should work, or lead you to the next error ;)

Its very heavy WIP please keep that in mind but keep also reporting any issue you find, we work on it for sure

**Comment by osi1880vr** [comment]
can you try again if it is still there?

**Comment by MrPalais** [comment]
![image](https://user-images.githubusercontent.com/89187184/194053672-0ec07790-5f64-4a5e-9aa2-aeb6ba99208f.png)
![image](https://user-images.githubusercontent.com/89187184/194053733-5147c476-87bc-4d88-bf90-f84c2b427ebe.png)

**Comment by MrPalais** [comment]
so I'm still using the version of the 27 sept...

**Comment by MrPalais** [comment]
it seems to work with the directory created, but I have this problem : 
content/models/sd-v1-4.ckpt not found
"content/" prefix is a real issue on windows...

**Comment by centrdev** [comment]
hey, getting the same error ; content/models/sd-v1-4.ckpt not found
